name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Maven Build and Unit Test
        run: ./mvnw clean package

      - name: SonarQube Analysis
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=spring-boot-mysql-docker-compose