name: AWS OIDC Test

on:
  push:
    branches:
      - main

jobs:
  test-aws:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      


      